name: Build the book
on:
  push:
    branches:
    - docs
concurrency: building
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: docs
        fetch-depth: 0 # all history for building
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '13'
    - name: Configure
      run: |
        git version
        git clone --depth=1 --branch=build https://github.com/aleen42/PersonalWiki.git temp
        mv -f temp/* ./
        mv temp/.bookignore ./
        git clone --depth=1 --branch=gh-pages https://github.com/aleen42/PersonalWiki.git gh-pages
    - name: Build
      run: |
        npm version
        npm install --no-save --no-audit
        npm run gitbook:install
        npm run gitbook:build
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
    - name: Deploy
      uses: aleen42/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{secrets.ACTION_TOKEN}}
        BRANCH: gh-pages
        FOLDER: gh-pages
